### ISSUE TITLE
'Namespace' object has no attribute 'model'

### ISSUE THREAD

**Issue by hongqingxie** [avinash-mishra/gan-style-transfer#1]
I have an issue when I train a new model, such as
C:\Users\MyUser\anaconda3\envs\exe\lib\site-packages\torchvision\transforms\transforms.py:257: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Traceback (most recent call last):
  File "main.py", line 321, in <module>
    main()
  File "main.py", line 41, in main
    train(args)
  File "main.py", line 128, in train
    model_dict = torch.load(args.model)  # or args.resume, matching what's in the line with style_model.load_state_dict
AttributeError: 'Namespace' object has no attribute 'model'

**Comment by kshru9** [comment]
I am having the same error. Is there any way to resolve it ? Please help.

> I have an issue when I train a new model, such as
> C:\Users\MyUser\anaconda3\envs\exe\lib\site-packages\torchvision\transforms\transforms.py:257: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
> "please use transforms.Resize instead.")
> Traceback (most recent call last):
> File "main.py", line 321, in
> main()
> File "main.py", line 41, in main
> train(args)
> File "main.py", line 128, in train
> model_dict = torch.load(args.model) # or args.resume, matching what's in the line with style_model.load_state_dict
> AttributeError: 'Namespace' object has no attribute 'model'

I am having the same error. Is there any way to resolve it. Please help. Thanks!
