### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by kshru9** [avinash-mishra/gan-style-transfer#3]
Traceback (most recent call last):
  File "main.py", line 320, in <module>
    main()
  File "main.py", line 41, in main
    train(args)
  File "main.py", line 145, in train
    utils.init_vgg16(args.vgg_model_dir)
  File "/content/drive/Shareddrives/ML/style-transfer/experiments/utils.py", line 103, in init_vgg16
    for (src, dst) in zip(vgglua.parameters()[0], vgg.parameters()):

I executed following command `! python main.py --epochs 2` in the colab. And its showing the above error. 

Anyone could help please

**Comment by avinash-mishra** [comment]
Let me try to reproduce it. If there will be any workaround I'll suggest it.
